@startuml



(NodeRegistration)<.. (generate registration request)
(generate registration request)<..(generate keypair):extends
(generate registration request)<..(hash public key as ID) :extends

Node ->(NodeRegistration)
(NodeRegistration)->Server:rpc

Server -> (store registration)
Server ->(generate response)
(generate response) <.. (RSA Signs Node's Public Key)
(generate response)<..(Collects List of Other Trusted Nodes)

Node <- (generate response):respond with nodes and signatures

Node ->(contact other trusted nodes)
@enduml
